---
name: Action

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    paths-ignore:
      - '*.md'

jobs:
  Local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fx31337/fx-data-generate-action@master
        with:
          OutputFile: "data.csv"
      - name: Runs local action
        uses: ./
        with:
          InputFile: "data.csv"
