---
name: Action

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    paths-ignore:
      - '*.md'

jobs:
  Generated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fx31337/fx-data-generate-action@master
        with:
          OutputFile: "data.csv"
      - name: Runs local convert action
        uses: ./
        with:
          InputFile: "data.csv"
          LogLevel: 3
  Downloaded:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fx31337/fx-data-download-action@master
        with:
          Pairs: "EURUSD"
          Years: 2020
          Months: 1
          Days: 1
      - name: Merges CSV files
        run: find . -name "*.csv" -and -not -name "data.csv" -exec cat {} "+" > data.csv
      - name: Runs local convert action
        uses: ./
        with:
          InputFile: "data.csv"
          LogLevel: 3
